name: Oroscopo Daily

on:

  schedule:
    - cron: '0 5 * * *'

  workflow_dispatch:

jobs:

  send:

    runs-on: ubuntu-latest

    steps:

      - name: Invia Newsletter

        run: |

          curl \
          "https://angelonline.altervista.org/backend/send-oroscopo.php?token=${{ secrets.OROSCOPO_TOKEN }}"
