name: Oroscopo Newsletter

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  send-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Invia newsletter oroscopo
        run: |
          curl -L "https://altervista.org"

