name: Oroscopo Newsletter
 
on:
schedule:
- cron: '0 4 * * *'
 
workflow_dispatch:
 
jobs:
*send-newsletter:
runs-on: ubun*u-latest
 
steps:
- name:*Invia newsletter oroscopo
*un: |
curl -L "https://a*gelonline.altervista.org/backend/o*oscopo_newsletter.php?token=ANONLA*2026"
